version: "3.9"

services:
  db:
    image: postgres
    container_name: products-pdfmake-db
    environment:
      restart: never
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: 'products-pdfmake'
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    container_name: products-pdfmake-backend
    command: yarn dev
    environment:
      NODE_ENV: development
    ports:
      - '3333:3333'
    volumes:
      - .:/src/app/products-pdfmake
      - /src/app/products-pdfmake/node_modules
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
